language: php

php:
    - 5.5
    - 5.6
sudo: false
cache:
   directories:
       - "$HOME/.composer/cache"
       - "$HOME/.php-cs-fixer"
before_script:
    - composer install --dev --no-interaction --prefer-source
    - mkdir -p "$HOME/.php-cs-fixer"
script:
    - phpunit --coverage-text --colors
    - bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --diff --verbose .
